name: Test - Base Workflow

on:
  push:
    branches:
      - master
      - rc
      - dev

jobs:
  base_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SET ENV VAR
        run: |
          echo "test=test" >> $GITHUB_ENV
      - name: echo env var
        run: echo ${{ env.test }}
